### ISSUE TITLE
Cant attach image

### ISSUE THREAD

**Issue by 1muen** [sskorol/mocha-allure2-reporter#5]
I use selenium and want to attach an image to my tests. However it doesnt work.
`            allure.attachment('step 2 attachment 2', Buffer.from(await browser.driver.takeScreenshot(), "base64"), allure2_js_commons_1.ContentType.PNG);      
`
The Image gets saved to /allure-results but not to /allure-report/data/attachments And it doesnt get displayed in the test report.

**Comment by sskorol** [comment]
@1muen sorry, seems like I missed this notification. Is the problem still actual? Can you show your package.json dependencies?
